basePath: /
definitions:
  model.Items:
    properties:
      description:
        type: string
      itemCode:
        type: string
      itemId:
        type: integer
      orderId:
        type: integer
      quantity:
        type: integer
    type: object
  model.Orders:
    properties:
      customerName:
        type: string
      items:
        items:
          $ref: '#/definitions/model.Items'
        type: array
      orderId:
        type: integer
      orderedAt:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: DTS H8 Assigment 2
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms
  title: Orders API
  version: "1.0"
paths:
  /orders:
    get:
      description: Get details of all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Orders'
            type: array
      summary: Get details of all orders
    post:
      description: Create new order
      parameters:
      - description: Create order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/model.Orders'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Orders'
      summary: Create new order
  /orders/{orderId}:
    delete:
      description: Delete existing order
      parameters:
      - description: todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete existing order
    put:
      description: Update existing order
      parameters:
      - description: order id
        in: path
        name: id
        required: true
        type: integer
      - description: order body
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/model.Orders'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Orders'
      summary: Update existing order
swagger: "2.0"
